drop table if exists proudcts;

create table products
(
    prod_id bigint generated by default as identity,
    prod_name varchar(255) not null,
    prod_price bigint not null,
    primary key (prod_id)
);